//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_bank:BaseModel
    {
    
    
    
    [EntityPrimKey("audit_bank")]
        public int id { get; set; }
    
    
    
        public Nullable<int> audit_id { get; set; }
    
    
    
        public Nullable<int> bank_id { get; set; }
    
    
    
        public Nullable<int> customer_id { get; set; }
    
        public virtual bank_account bank_account { get; set; }
    }
}
