//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaf:BaseModel
    {
    
    
    
    [EntityPrimKey("leaf")]
        public int id { get; set; }
    
    
    
        public Nullable<int> owner_id { get; set; }
    
    
    
        public Nullable<int> type { get; set; }
    
    
    
        public Nullable<System.DateTime> date_start { get; set; }
    
    
    
        public Nullable<System.DateTime> date_end { get; set; }
    
    
    
        public string reason { get; set; }
    
    
    
        public string memo { get; set; }
    
    
    
        public Nullable<int> receiver_id { get; set; }
    
    
    
        public Nullable<int> auditor_id { get; set; }
    
    
    
        public string tel { get; set; }
    
    
    
        public Nullable<int> status { get; set; }
    
    
    
        public Nullable<System.DateTime> date_created { get; set; }
    
    
    
        public Nullable<System.DateTime> date_updated { get; set; }
    }
}
