//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecture:BaseModel
    {
        public lecture()
        {
            this.lecture_customer = new HashSet<lecture_customer>();
        }
    
    
    
    
    [EntityPrimKey("lecture")]
        public int id { get; set; }
    
    
    
        public string form { get; set; }
    
    
    
        public string title { get; set; }
    
    
    
        public string teacher { get; set; }
    
    
    
        public Nullable<System.DateTime> date_at { get; set; }
    
    
    
        public string city { get; set; }
    
    
    
        public string address { get; set; }
    
    
    
        public string sponsor { get; set; }
    
    
    
        public string co_sponsor { get; set; }
    
    
    
        public string customer_target { get; set; }
    
    
    
        public Nullable<int> creator_id { get; set; }
    
    
    
        public Nullable<System.DateTime> date_created { get; set; }
    
    
    
        public Nullable<System.DateTime> date_updated { get; set; }
    
    
    
        public Nullable<int> charge_id { get; set; }
    
        public virtual member member { get; set; }
        public virtual member member1 { get; set; }
        public virtual ICollection<lecture_customer> lecture_customer { get; set; }
    }
}
