//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail:BaseModel
    {
    
    
    
    [EntityPrimKey("mail")]
        public int id { get; set; }
    
    
    
        public string type { get; set; }
    
    
    
        public string owner { get; set; }
    
    
    
        public string letter_type { get; set; }
    
    
    
        public string merchant { get; set; }
    
    
    
        public string code { get; set; }
    
    
    
        public Nullable<System.DateTime> date_at { get; set; }
    
    
    
        public string description { get; set; }
    
    
    
        public string file_url { get; set; }
    
    
    
        public Nullable<int> creator_id { get; set; }
    
    
    
        public Nullable<System.DateTime> date_created { get; set; }
    
    
    
        public Nullable<System.DateTime> date_updated { get; set; }
    
    
    
        public string address { get; set; }
    
    
    
        public Nullable<int> audit_id { get; set; }
    
    
    
        public string order_name { get; set; }
    
    
    
        public string order_source { get; set; }
    
    
    
        public Nullable<int> order_id { get; set; }
    
    
    
        public string order_code { get; set; }
    
        public virtual member member { get; set; }
    }
}
