//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class member:BaseModel
    {
        public member()
        {
            this.customers = new HashSet<customer>();
            this.customers1 = new HashSet<customer>();
            this.customers2 = new HashSet<customer>();
            this.customers3 = new HashSet<customer>();
            this.customers4 = new HashSet<customer>();
        }
    
    
    
    
    [EntityPrimKey("member")]
        public int id { get; set; }
    
    
    
        public Nullable<int> organization_id { get; set; }
    
    
    
        public Nullable<int> area_id { get; set; }
    
    
    
        public Nullable<int> position_id { get; set; }
    
    
    
        public string username { get; set; }
    
    
    
        public string name { get; set; }
    
    
    
        public string english_name { get; set; }
    
    
    
        public string password { get; set; }
    
    
    
        public string mobile { get; set; }
    
    
    
        public Nullable<System.DateTime> hiredate { get; set; }
    
    
    
        public Nullable<System.DateTime> birthday { get; set; }
    
    
    
        public Nullable<int> status { get; set; }
    
    
    
        public Nullable<System.DateTime> date_created { get; set; }
    
    
    
        public Nullable<System.DateTime> date_updated { get; set; }
    
        public virtual area area { get; set; }
        public virtual organization organization { get; set; }
        public virtual position position { get; set; }
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<customer> customers1 { get; set; }
        public virtual ICollection<customer> customers2 { get; set; }
        public virtual ICollection<customer> customers3 { get; set; }
        public virtual ICollection<customer> customers4 { get; set; }
    }
}
