//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier:BaseModel
    {
        public supplier()
        {
            this.accounting_item = new HashSet<accounting_item>();
            this.audits = new HashSet<audit>();
            this.patents = new HashSet<patent>();
            this.reg_abroad = new HashSet<reg_abroad>();
            this.reg_internal = new HashSet<reg_internal>();
            this.sub_audit = new HashSet<sub_audit>();
            this.trademarks = new HashSet<trademark>();
            this.accountings = new HashSet<accounting>();
            this.annual_exam = new HashSet<annual_exam>();
            this.histories = new HashSet<history>();
        }
    
    
    
    
    [EntityPrimKey("supplier")]
        public int id { get; set; }
    
    
    
        public string name { get; set; }
    
    
    
        public Nullable<System.DateTime> date_created { get; set; }
    
    
    
        public Nullable<System.DateTime> date_updated { get; set; }
    
        public virtual ICollection<accounting_item> accounting_item { get; set; }
        public virtual ICollection<audit> audits { get; set; }
        public virtual ICollection<patent> patents { get; set; }
        public virtual ICollection<reg_abroad> reg_abroad { get; set; }
        public virtual ICollection<reg_internal> reg_internal { get; set; }
        public virtual ICollection<sub_audit> sub_audit { get; set; }
        public virtual ICollection<trademark> trademarks { get; set; }
        public virtual ICollection<accounting> accountings { get; set; }
        public virtual ICollection<annual_exam> annual_exam { get; set; }
        public virtual ICollection<history> histories { get; set; }
    }
}
