//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_record:BaseModel
    {
    
    
    
    [EntityPrimKey("tax_record")]
        public int id { get; set; }
    
    
    
        public int master_id { get; set; }
    
    
    
        public Nullable<int> deal_way { get; set; }
    
    
    
        public Nullable<int> audit_id { get; set; }
    
    
    
        public string audit_code { get; set; }
    
    
    
        public Nullable<System.DateTime> sent_date { get; set; }
    
    
    
        public Nullable<int> submit_reviewer_id { get; set; }
    
    
    
        public Nullable<System.DateTime> submit_review_date { get; set; }
    
    
    
        public string submit_review_moment { get; set; }
    
    
    
        public Nullable<int> review_status { get; set; }
    
    
    
        public string memo { get; set; }
    
    
    
        public string attachment { get; set; }
    
    
    
        public Nullable<int> creator_id { get; set; }
    
    
    
        public Nullable<System.DateTime> date_created { get; set; }
    
    
    
        public Nullable<System.DateTime> date_updated { get; set; }
    }
}
